---
title: "Assignment3A-KCH-Approach"
author: "Kailot C. Harris"
date: "2026/09/16"
format: html
theme: cosmo
editor: visual
---

## Introduction and Overview

Window functions are a useful method to generate a new column of data calculated from previous columns while maintaining the original columns in tact. A common example is calculating a moving average column from data in preceding rows. Functions like `sum()`, `summarize()`, or `count()` are not window functions because they flatten the data into singular outputs, rather than maintaining the table rows.

In this assignment, window functions will be utilized to calculate rolling averages (year-to-date and six-day moving averages) of financial data. The data will be sourced from an open data provider of stocks traded on the New York Stock Exchange as of Friday, September 11, 2026. Since moving-averages are useful for stock price analysis, there are several types of moving average calculations used in this context. For instance, a 5-day simple-moving-average (SMA5) is calculated as the standard mean of the last five days' observations (e.g. closing prices). Alternatively, the 5-day exponential-moving-average (EMA5) is a weighted moving average, which more heavily weighs recent data over temporally older data. This older data has an exponential decay pattern to its weighing, so the EMA is utilized as a more reactive alternative to SMA calculations. By contrast, the SMA calculations are less responsive to intra-day fluctuations and can provide smoother trends.

Anticipated challenges in this assignment include maintaining a reproducible pipeline from ingestion to analysis, identifying a reliable and free data source, and appropriately applying window functions in R.
